[package]
name = "darwin-rs"
version = "0.1.0"
authors = ["Willi Kappler, grandor@gmx.de"]
license = "MIT"
description = "Evolutionary algorithms library written in Rust."
readme = "README.md"
repository = "https://github.com/willi-kappler/darwin-rs"
exclude = ["*.png", "example"]
keywords = ["evolutionary", "algorithm", "EA"]

[dependencies]
time = "0.1"
jobsteal = "0.4"
